### ISSUE TITLE
Fail: java.lang.IllegalArgumentException: URI is not hierarchical

### ISSUE THREAD

**Issue by cicika** [mtkopone/scct#22]
```
java.lang.IllegalArgumentException: URI is not hierarchical
at java.io.File.<init>(File.java:363)
at reaktor.scct.Env$$anonfun$2.apply(Env.scala:56)
at reaktor.scct.Env$$anonfun$2.apply(Env.scala:56)
at scala.Option.getOrElse(Option.scala:108)
at reaktor.scct.Env.coverageFile(Env.scala:56)
at reaktor.scct.Coverage$.readMetadata(Coverage.scala:41)
at reaktor.scct.Coverage$.init(Coverage.scala:23)
at reaktor.scct.Coverage$.tryInit(Coverage.scala:14)
at reaktor.scct.Coverage$.invoked(Coverage.scala:34)
```

Apparently, coverage.data is looked for in the generated .jar (projectName-version-scct.jar!/coverage.data) and not in scct-classes directory.

I am using Scala 2.9.1 with sbt 0.11.3 and your own sbt plugin (https://github.com/mtkopone/sbt-scct) on a multi module project and I'm rendered clueless with what to do. I've tried other plugins, with absolutely same result.

Any advice?

Thanks!

**Comment by cicika** [comment]
I've got it all to work, but with certain changes in env properties in Env.scala as well as in the plugin.

Cheers!

**Comment by mtkopone** [comment]
Cool. 

I've been away on summer vacation, so response times from this end have been a bit slow.

The 0.2-SNAPSHOT version of scct with the new sbt-scct-plugin is still a bit alpha quality, I'm hoping to finish it in the near future, and then write instructions for use.

**Comment by cicika** [comment]
Hopefully, holiday was good :)

Basically, I just set the coverage.data file as a system property in the
sbt plugin, which got it to work,
however there are still some issues overall.

On Mon, Jul 30, 2012 at 9:46 AM, Mikko Koponen <
reply@reply.github.com

**Comment by benoitheinrich** [comment]
Hi guys,

I'm using the latest version 0.2-SNAPSHOT of scct and I'm having the same issue.
What were the changes you've had to do to your Env.scala and to the plugin?
Did these changes been merged to the master branch?

Cheers for helping

**Comment by cicika** [comment]
As I recall, this was the solution::

Basically, I just set the coverage.data file as a system property in the
sbt plugin, which got it to work

**Comment by benoitheinrich** [comment]
Hi cicika,

Thanks for the reply, but I've got another question :)
What value do you give it? does it need to be an existing file or will it create the file automatically?

Cheers :)

**Comment by cicika** [comment]
System.setProperty("scct.coverage.file", classesDir.getAbsolutePath.toString + "/coverage.data")

Added to testOptions in ScctTest (line 48, my addition falls on line 60), file will be created automatically as a result of coverage analysis.

By the way, sorry for slow initial response.

**Comment by benoitheinrich** [comment]
Hi Cicika, 

I tried to set the System property but when I do the following in my Build.scala:

``` scala
  val commonSettings = buildSettings ++ ScctPlugin.instrumentSettings ++ Seq(
    testOptions in ScctTest <+= (scalaVersion in Test, classDirectory in Test) map {
      (scalaVer, classesDir) => Tests.Setup {
        () =>
          System.setProperty("scct-test-scala-version", scalaVer)
          System.setProperty("scct.coverage.file", classesDir.getAbsolutePath + "/coverage.data")
      }
    }
  )
```

Then it fails with the error:

```
 [error] /.../project/Build.scala:139: not found: value ScctTest
 [error]     testOptions in ScctTest <+= (scalaVersion in Test, classDirectory in Test) map 
```

Do you have a link to an example build file I could be looking at? maybe a gist if you have one?

btw - I tried to change the "testOptions in ScctTest" by "testOptions in Test" and then it compiles, but the tests fail with the same error.

Thanks for all your help, it's very much appreciated :)
/Benoit

**Comment by justinp** [comment]
I got this to work by disabling "exportJars" in my sbt projects.  That may not be a great solution but at least you can turn it off, run your coverage report and turn it back on as a workaround.

-Justin

**Comment by ghost** [comment]
Same issue reproduced on multilevel project. I've fixed it with next changes in Build.scala:

<pre>
  // def -> need to be recalculated for each child project 
  def scctOpts = ScctPlugin.instrumentSettings ++
    Seq(testOptions in ScctPlugin.ScctTest  <+= (scalaVersion in Test, classDirectory in ScctPlugin.Scct) map {
    (scalaVer, classesDir) => Tests.Setup {
      () =>
        System.setProperty("scct-test-scala-version", scalaVer)
        System.setProperty("scct.coverage.file", classesDir.getAbsolutePath + "/coverage.data")
    }
  })
  lazy val root = Project(id = "parent", base = file("."))
      settings (ScctPlugin.mergeReportSettings: _*) aggregate(first, second)
  lazy val firstChild = Project(id = "firstchild", base = file("first"))
      settings (scctOpts: _*)
  lazy val secondChild = Project(id = "secondchild", base = file("second"))
      settings (scctOpts: _*)
}
</pre>

**Comment by gshakhn** [comment]
@benoitheinrich You have to import ScctPlugin.ScctTest

Unfortunately, I still have a problem with analyzing projects with jars. We have a multi-project sbt configuration. The projects that don't export jars work fine, but the ones that do time out waiting for a coverage report. I'm not sure what the exact problem is, but it looks like the `scct.%s.fire.report` system property doesn't work correctly with projects that export jars.

**Comment by gshakhn** [comment]
Ignore my comment regarding the system property. It looks like the HtmlReporter never finishes. If I kill sbt via Ctrl-C, I get a stacktrace similar to the following:

```
Exception in thread "Thread-2" java.io.FileNotFoundException: <project-root-directory>/<path-to-source-file>(No such file or directory)
at java.io.FileInputStream.open(Native Method)
 at java.io.FileInputStream.<init>(FileInputStream.java:138)
 at scala.io.Source$.fromFile(Source.scala:90)
 at scala.io.Source$.fromFile(Source.scala:75)
 at scala.io.Source$.fromFile(Source.scala:80)
 at reaktor.scct.report.SourceLoader.linesFor(SourceLoader.scala:8)
 at reaktor.scct.report.SourceFileHtmlReporter$.report(SourceFileHtmlReporter.scala:11)
 at reaktor.scct.report.HtmlReporter$$anonfun$sourceFileReports$1.apply(HtmlReporter.scala:92)
 at reaktor.scct.report.HtmlReporter$$anonfun$sourceFileReports$1.apply(HtmlReporter.scala:91)
 at scala.collection.immutable.RedBlackTree$.foreach(RedBlackTree.scala:79)
 at scala.collection.immutable.RedBlackTree$.foreach(RedBlackTree.scala:78)
 at scala.collection.immutable.RedBlackTree$.foreach(RedBlackTree.scala:78)
 at scala.collection.immutable.RedBlackTree$.foreach(RedBlackTree.scala:78)
 at scala.collection.immutable.RedBlackTree$.foreach(RedBlackTree.scala:78)
 at scala.collection.immutable.RedBlackTree$.foreach(RedBlackTree.scala:78)
 at scala.collection.immutable.TreeMap.foreach(TreeMap.scala:202)
 at reaktor.scct.report.HtmlReporter.sourceFileReports(HtmlReporter.scala:91)
 at reaktor.scct.report.HtmlReporter.report(HtmlReporter.scala:20)
 at reaktor.scct.Coverage$.report(Coverage.scala:58)
 at reaktor.scct.Coverage$$anon$1.run(Coverage.scala:67)
```

The issue is that the file exists at `<project-root-directory>/<subproject-name>/<path-to-source-file>`

For some reason, it's trying to find the source file in the root project instead of the actual project it's in.

**Comment by gshakhn** [comment]
The reason it was picking the the wrong directory is because it couldn't read the `scct.basedir` property. The sbt task creates a properties file in `scct-test-classes`, However, this properties file is not on the classpath if the project has `exportJars` set to true. I added a copy of the properties file as a managed resource. The end result looks like:

```
def scctOpts = ScctPlugin.instrumentSettings ++ Seq(
  testOptions in ScctTest <+= (scalaVersion in Scct, classDirectory in Scct) map {
    (scalaVer, classesDir) => Tests.Setup {
      () =>
        System.setProperty("scct-test-scala-version", scalaVer)
        System.setProperty("scct.coverage.file", classesDir.getAbsolutePath + "/coverage.data")
    }
  },
  resourceGenerators in Scct <+= (resourceManaged in Scct, name in Scct, baseDirectory in Scct, scalaSource in Scct, scctReportDir) map { (dir, n, base, src, reportDir) =>
      val props = new Properties()
      props.setProperty("scct.basedir", base.getAbsolutePath)
      props.setProperty("scct.report.hook", "system.property")
      props.setProperty("scct.project.name", n)
      props.setProperty("scct.report.dir", reportDir.getAbsolutePath)
      props.setProperty("scct.source.dir", src.getAbsolutePath)
      val out = dir / "scct.properties"
      IO.write(props, "Env for scct test run and report generation", out)
      Seq(out)
  }
)
```
